<?php

/**
 * Created by PhpStorm.
 * User: Nimo
 * Date: 08/08/2016
 * Time: 10:05 CH
 */
class index_model extends base_model
{
    public $table = "posts";

    public function getAll($table = null)
    {
        return parent::getAll($this->table); // TODO: Change the autogenerated stub
    }

    public function getTotalPost()
    {
        $sql = "SELECT count(*) as total_post FROM " . $this->table;
        $this->stmt = $this->conn->prepare($sql);
        $this->stmt->execute();
        return $this->stmt->fetch();
//        return $this->conn->

    }

    public function getData($limit = 5, $page = 1)
    {
        $sql = "SELECT p.*, u.user_name FROM posts p INNER JOIN users u ON p.user_ID = u.id  ORDER BY p.created_time DESC";
        if ($limit !== 'all') {
            $sql .= " LIMIT " . (($page - 1) * $limit) . "," . $limit;
        }

//        echo "<pre>";var_dump($sql);echo "</pre>"; exit;
        $this->stmt = $this->conn->prepare($sql);

        $this->stmt->execute();

        return $this->stmt->fetchAll();
    }
}