<?php

/**
 * Created by PhpStorm.
 * User: Nimo
 * Date: 10/08/2016
 * Time: 11:51 CH
 */
class post_admin_model extends base_model
{
    public function getListCategories()
    {
        return parent::getAll('categories');

    }

    public function insertPost($title, $content, $category, $status)
    {
        $created_time = date('y-m-d');
        $views = 0;
        $user_id = $_SESSION['admin_id'];

        $sql = "INSERT INTO posts (title, content,created_time,last_edit,views, user_ID,category_ID,status)
                        VALUES  (:title, :content,:created_time,:last_edit,:views, :user_ID, :category_ID,:status)";
        try {
            $this->stmt = $this->conn->prepare($sql);
            $this->stmt->bindParam(":title", $title);
            $this->stmt->bindParam(":content", $content);
            $this->stmt->bindParam(":created_time", $created_time);
            $this->stmt->bindParam(":last_edit", $created_time);
            $this->stmt->bindParam(":views", $views, PDO::PARAM_INT);
            $this->stmt->bindParam(":user_ID", $user_id, PDO::PARAM_INT);
            $this->stmt->bindParam(":category_ID", $category, PDO::PARAM_INT);
            $this->stmt->bindParam(":status", $status, PDO::PARAM_INT);
            $this->stmt->execute();
        } catch (PDOException $e) {
            die($e->getMessage());
        }
        if ($this->conn->lastInsertId() > 0) {
            return true;
        } else {
            return false;
        }

    }

    public function getPostById($id)
    {
        return parent::getById('posts', $id); // TODO: Change the autogenerated stub
    }
}